# Generated by Django 4.0.1 on 2022-02-25 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('registration_number', models.CharField(max_length=8, unique=True)),
                ('campus', models.CharField(max_length=255)),
                ('faculty', models.CharField(max_length=255)),
                ('course', models.CharField(max_length=255)),
                ('mode_of_study', models.CharField(max_length=255)),
            ],
        ),
    ]
