# Generated by Django 4.0.1 on 2022-02-25 16:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PossessedBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('return_delay_fine', models.IntegerField(default=0)),
                ('book', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='possessedbook', to='books.book')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='possessedbooks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
