# Generated by Django 4.0.1 on 2022-02-25 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn', models.CharField(max_length=13)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('language', models.CharField(max_length=255)),
                ('pages', models.IntegerField()),
                ('year_published', models.IntegerField()),
                ('publisher', models.CharField(max_length=255)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='categories.category')),
            ],
        ),
    ]
